In [196]:
import pandas as pd

In [197]:
unique = pd.read_csv("unique.csv")
df = pd.read_csv("download (2).csv")

In [198]:
df

        Code      Type           Category
0      2 405      Food            Dessert
1      5 046      Food              drink
2      5 048      Food              drink
3      5 047      Food              drink
4      5 042      Food              drink
...      ...       ...                ...
17109  10967      Food  meat_fish_poultry
17110  10356      Food              drink
17111   8409  Non-Food      personal_care
17112   4288      Food              snack
17113   4292      Food              snack

[17114 rows x 3 columns]

In [199]:
merged_df = pd.merge(df, unique, on="Code", how="left")
merged_df

,Code,Type,Category,Product
0,2 405,Food,Dessert,100% Vkus Marojenoe Lyod 70gr
1,5 046,Food,drink,18+ Energy 330ml
2,5 048,Food,drink,18+ Energy 450ml
3,5 047,Food,drink,18+ Energy 250ml
4,5 042,Food,drink,18+ Energy Arbuz 450ml
...,...,...,...,...
18117,10967,Food,meat_fish_poultry,Whiskas Dlya Kotyat Indeyka Morkovyu 350gr
18118,10356,Food,drink,Xrus Team Sir suxariki 27gr
18119,8409,Non-Food,personal_care,Yumos gel dlya stirki 2520ml
18120,4288,Food,snack,"Zuly Baraka, маринадланган, шиша банка 1 л."
18121,4292,Food,snack,"Zuly Baraka, Тузланган,шиша банка 720 г. Pomid..."

In [200]:
merged_df[merged_df["Product"].str.contains("osvejitel")]

,Code,Type,Category,Product
11802,9579,Unknown,Unknown,Wellnax Ball osvejitel dlya obuvi chyorniy 2sht
11803,9588,Unknown,Unknown,Wellnax Lemon osvejitel dlya mashina 8gr 2sht
12694,6090,Unknown,Unknown,Glade osvejitel Svejest Belya 269ml
16003,10457,Food,drink,Glade osvejitel Nebo i Morskaya Sol 269ml
16532,9580,Unknown,Unknown,Wellnax Ball osvejitel dlya obuvi siniy 2sht
16533,9592,Food,fruit_vegetable,Wellnax Mangoliya osvejitel dlya shkafchik 1sh...
16534,9601,Food,drink,Wellnax Morskoy osvejitel dlya tuleta 3sht 57gr
16540,9587,Unknown,Unknown,Wellnax Orxideya osvejitel dlya mashina 8gr 2sht
16541,9591,Unknown,Unknown,Wellnax Roza osvejitel dlya shkafchik 1sht 20gr
16542,9599,Food,condiment,Wellnax Sosna osvejitel dlya tuleta 3sht 57gr
16543,9586,Unknown,Unknown,Wellnax Tropical osvejitel dlya mashina 8gr 2sht
17446,9581,Unknown,Unknown,Wellnax Ball osvejitel dlya obuvi fioletoviy 2sht
17447,9589,Unknown,Unknown,Wellnax Lemon osvejitel dlya mashina 1sht 20gr
17448,9585,Unknown,Unknown,Wellnax Tropical osvejitel dlya mashina 1sht 20gr
17866,9615,Food,condiment,Bref Sosna osvejitel dlya tualeta 3sht 50gr
18113,9602,Unknown,Unknown,Wellnax Lemon osvejitel dlya tuleta 3sht 57gr

In [201]:
merged_df[merged_df["Product"].str.contains("Koshek")]

         Code     Type Category                            Product
1271      952  Unknown  Unknown      Darling Korm Dlya Koshek 75gr
1903    8 960  Unknown  Unknown        Felix Korm Dlya Koshek 75gr
2668    9 928  Unknown  Unknown      Kitekat Korm Dlya Koshek 85gr
2714    8 957  Unknown  Unknown                Korm Dlya Koshek KG
3636    8 958  Unknown  Unknown         Myau Korm Dlya Koshek 80gr
4390    2 360  Unknown  Unknown   Probalance Korm Dlya Koshek 85gr
5465   12 147  Unknown  Unknown  Utka Darlit Korm Dlya Koshek 75gr
5588   11 685  Unknown  Unknown      Whiskas Korm Dlya Koshek 75gr
8810     8957  Unknown  Unknown                Korm Dlya Koshek KG
9750     8958  Unknown  Unknown         Myau Korm Dlya Koshek 80gr
12637    8960  Unknown  Unknown        Felix Korm Dlya Koshek 75gr
12846    9928  Unknown  Unknown      Kitekat Korm Dlya Koshek 85gr
13593   12147  Unknown  Unknown  Utka Darlit Korm Dlya Koshek 75gr
13654   11685  Unknown  Unknown      Whiskas Korm Dlya Koshek 75gr
15214    2360  Unknown  Unknown   Probalance Korm Dlya Koshek 85gr
17694    1729  Unknown  Unknown       Justin Korm Dlya Koshek 75gr
17710   10966  Unknown  Unknown        Lapka Korm Dlya Koshek 85gr

In [202]:
merged_df[merged_df["Type"] == "Unknown"]

         Code     Type Category                                        Product
170    13 747  Unknown  Unknown                     Alif Jvachka Assorti 12sht
171    13 085  Unknown  Unknown                      Alif Jvachka Assorti 1sht
174     7 894  Unknown  Unknown                         Aloe Vera Original 0.5
175     7 860  Unknown  Unknown                         Aloe Vera Original 1.5
181    10 666  Unknown  Unknown   Alpina Mnogoseliviye Salfetki 27sm33sm 20sht
...       ...      ...      ...                                            ...
18108   12129  Unknown  Unknown   Uvelka Dobroe Utro ovsyanaya s Yablokom 40gr
18111    6407  Unknown  Unknown                             Vileda Glitzi 2sht
18113    9602  Unknown  Unknown  Wellnax Lemon osvejitel dlya tuleta 3sht 57gr
18114    5199  Unknown  Unknown            Wellnax Obodok Dlya Tualeta 2 Lemon
18115    5231  Unknown  Unknown   Wellnax Obodok Dlya Tualeta Pine Forest 57gr

[5123 rows x 4 columns]

In [203]:
import pandas as pd

def simplify_categories_20(df, category_col='Category', type_col='Type'):
    # Mapping 20 kategoriya uchun
    category_mapping = {
        'dessert': 'Dessert',
        'Dessert': 'Dessert',
        'drink': 'Drink',
        'dairy': 'Dairy',
        'bakery': 'Bakery',
        'grain_pasta': 'Grains & Pasta',
        'beans_legumes': 'Grains & Pasta',
        'nut': 'Grains & Pasta',
        'Snack': 'Snack',
        'snack': 'Snack',
        'fruit_vegetable': 'Fruit & Vegetable',
        'Fruit_Vegetable': 'Fruit & Vegetable',
        'meat_fish_poultry': 'Meat & Fish',
        'condiment': 'Pantry',
        'Condiment': 'Pantry',
        'canned_frozen_dried': 'Pantry',
        'ingredients': 'Pantry',
        'baby food': 'Baby',
        'baby_care': 'Baby',
        'Baby_Care': 'Baby',
        'personal_care': 'Personal Care',
        'Personal_Care': 'Personal Care',
        'household': 'Household',
        'Household': 'Household',
        'health_medical': 'Health & Medical',
        'stationery_office': 'Stationery & Office',
        'clothing_accessories': 'Clothing',
        'media': 'Media & Electronics',
        'electronics_accessories': 'Media & Electronics',
        'tools_hardware': 'Tools & Home',
        'home_decor': 'Tools & Home',
        'packaging': 'Packaging',
        'Other Food': 'Other Food',
        'Other Non-Food': 'Other Non-Food',
        'other_non_food': 'Other Non-Food',
        'Unknown': 'Unknown'
    }

    # Food toifalari
    food_categories = {
        'Dessert', 'Drink', 'Dairy', 'Bakery', 'Grains & Pasta', 'Snack',
        'Fruit & Vegetable', 'Meat & Fish', 'Pantry', 'Baby', 'Other Food'
    }

    # Kategoriya soddalashtirish
    df[category_col] = df[category_col].map(category_mapping).fillna('Other Non-Food')

    # Type aniqlash
    def assign_type(cat):
        if cat == 'Unknown':
            return 'Unknown'
        elif cat in food_categories:
            return 'Food'
        else:
            return 'Non-Food'

    df[type_col] = df[category_col].apply(assign_type)
    return df
merged_df = simplify_categories_20(merged_df, category_col='Category', type_col='Type')

In [204]:
merged_df.sample(15)

,Code,Type,Category,Product
1819,11 998,Food,Fruit & Vegetable,Euro Food Kukuruza Sladkaya 300gr
5748,13 031,Unknown,Unknown,Yess Semechka Tuzli 190gr
11002,8517,Food,Pantry,SAGBAN Sosiska Molochniy Extra KG
13135,8213,Unknown,Unknown,Nutrilak Kasha №4 18oydan 600gr
8875,1857,Food,Bakery,Krember Bruni Keks Karamel 190gr 10sht
16877,10254,Food,Drink,Sutash Ayran 200ml
2102,10 375,Non-Food,Personal Care,Gillette Britva №2 2sht
16780,6653,Food,Snack,Alyonka shokolad s molochno-zlakovoy nachinkoy...
7077,4466,Unknown,Unknown,Cif Crem Rozoviyt Svejesti 500ml
16322,7892,Food,Snack,Ritter Sport shokolad mini assorti 16.67gr
7102,6029,Food,Drink,Co Barrede Chocolat Multizlakoviye Assorti KG
9974,2918,Food,Drink,Nestle Santal Suv Gazlangan 1.5Lt
1254,10 288,Food,Bakery,Daily Bread bakery Toster sredniy Xleb
878,11 874,Non-Food,Personal Care,Charmelle Bazelika milo 140gr
4227,11 349,Food,Baby,Perla Bolalar Taglikligi Extra Large №6 12sht

In [205]:
merged_df["Category"].nunique()

21

In [208]:
unk = merged_df[(merged_df["Category"] == "Unknown")]

In [209]:
unk.to_csv("unknowns.csv")